# Generated by Django 2.2.3 on 2019-08-02 02:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bet', '0002_pari'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match', models.CharField(max_length=256)),
                ('home', models.CharField(blank=True, max_length=256, null=True)),
                ('predict', models.CharField(blank=True, max_length=256, null=True)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('cote', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('gain', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0.01)])),
            ],
        ),
        migrations.DeleteModel(
            name='Pari',
        ),
    ]
