# Generated by Django 2.2.3 on 2019-08-02 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bet', '0003_auto_20190802_0219'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Parie',
            new_name='Betting',
        ),
    ]
