# Generated by Django 2.2.3 on 2019-08-02 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bet', '0004_auto_20190802_0227'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pari',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match', models.CharField(max_length=256)),
                ('home', models.CharField(blank=True, max_length=256, null=True)),
                ('predict', models.CharField(blank=True, max_length=256, null=True)),
                ('montant', models.CharField(max_length=12, null=True)),
                ('cote', models.CharField(max_length=64)),
                ('gain', models.CharField(max_length=64)),
            ],
        ),
    ]
